---
title: "Weather Information Preferences"
author: "Author: Johnson W. Ahiadorme"
date: "`r format (Sys.Date(), '%A, %B %d, %Y')`"
output: 
  ioslides_presentation:
    logo: images/sunstar.png
params:
  region: 
    value: Mountain
    input: select
    choices: ["East North Central","East South Central", 
              "Middle Atlantic","Mountain", "New England", 
              "Pacific","South Atlantic", "West North Central",
              "West South Central"]
---

```{r, echo=FALSE, message=FALSE, warning=FALSE }
knitr::read_chunk("code/setup.R")
```

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadData}
```


```{r child="text/Backgroundsection.Rmd"}
```


```{r child="text/PurposeSection.Rmd"}
```


## Demographics of Survey Respondents in a Merged Table

This section provides demographic summary tables for the `r nrow(sdat)` survey respondents.

```{r MakeTable, code=readLines("code/MakeTable.R")}
```


## Weather Source Preference by Gender

Finally, here is a breakdown of the `r nrow(sdat)` survey respondents for the `r params$region` region of the US on how they check their daily weather by gender.

```{r}
knitr::read_chunk("code/MakeChart.R")
```

```{r MakeCharts}
```


